version: '3.8'

services:
  web:
    build: .
    container_name: fyle-intern-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: fyle-db
    environment:
      POSTGRES_USER: fyle_user
      POSTGRES_PASSWORD: fyle_password
      POSTGRES_DB: fyle_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
